#!/usr/bin/perl -w

use strict;
use warnings;
use feature qw( switch );

use Term::ANSIColor;
use Cwd;
use Data::Dumper;

use lib "/usr/lib/smoothwall";
use header qw( :standard );

my $mods_home = "/var/smoothwall/mods";
my $modsa_home = "/var/smoothwall/mods-available";
my $mod_name = "fail2ban";
my %mask2cidr = (
	'255.255.255.252'	=>	'30',
	'255.255.255.248'	=>	'29',
	'255.255.255.240'	=>	'28',
	'255.255.255.224'	=>	'27',
	'255.255.255.192'	=>	'26',
	'255.255.255.128'	=>	'25',
	'255.255.255.0'		=>	'24',
	'255.255.0.0'		=>	'16',
	'255.0.0.0'		=>	'8',
);
my (%ethernet_settings);
&readhash("/var/smoothwall/ethernet/settings", \%ethernet_settings);

my $cwd = getcwd();
given ($cwd) {
	when ('/root/swe-fail2ban') {
		print colored("Looks like you're in the dev directory.  Would you like to install this mod to your smoothie?\n", "bold cyan");
		my $ans = readline();
		chomp($ans);
		if ($ans =~ /^[Yy](?:es)?/) {
			system("/bin/mkdir -p $modsa_home") unless ( -d $modsa_home );
			system("/bin/mkdir -p $modsa_home/$mod_name") unless ( -d "$modsa_home/$mod_name");
			system("/bin/cp -rf * $modsa_home/$mod_name/");
			chdir("$modsa_home/$mod_name");
			print colored("Whitelisting GREEN IP....\n", "bold cyan");
			my @newlines;
			open CONFIN, "<etc/fail2ban/jail.conf" or die colored("There was a problem opening jail.conf: $!", "bold red");
			while (my $line = <CONFIN>) {
				chomp($line);
				if ($line =~ /^ignoreip/) {
					$line .= " $ethernet_settings{'GREEN_NETADDRESS'}/$mask2cidr{$ethernet_settings{'GREEN_NETMASK'}}";
				}
				push @newlines, $line;
			}
			close CONFIN or die colored("There was a problem closing jail.conf: $!", "bold red");
			open CONFOUT, ">/tmp/fail2ban.tmp.conf" or die colored("Couldn't open output tmp file: $!", "bold red");
			foreach my $line ( @newlines ) {
				print CONFOUT $line."\n";
			}
			close CONFOUT or die colored("There was a problem closing output tmp file: $!", "bold red");
			system("/bin/cp -f /tmp/fail2ban.tmp.conf $modsa_home/$mod_name/etc/fail2ban/jail.conf");
			print colored("Patching /etc/bashrc....\n", "bold cyan");
			system("/bin/grep -q 'modification by swe-fail2ban' /etc/bashrc || /bin/cat _etc_bashrc.add >> /etc/bashrc");
			chdir("$mods_home");
			system("/bin/ln -snf ../mods-available/fail2ban fail2ban");
			# fail2ban insists that stuff be in /etc/fail2ban, even with the alternate config
			chdir("/etc/");
			system("/bin/ln -snf $mods_home/fail2ban/etc/fail2ban fail2ban");
			system("/bin/touch $modsa_home/$mod_name/installed");
			print colored("The fail2ban mod for Smoothwall Express should now be enabled and configured.\n", "bold cyan");
			print colored("To use the fail2ban-client command immediately, \"source /etc/bashrc\".  Otherwise, log out, then back in.\n", "bold cyan");
		} else {
			print colored("Quitting.\n", "bold red");
			exit 0;
		}
	}
	when ('/tmp/fail2ban') {
		print colored("Looks like you're in the tmp directory.  Would you like to install this mod to your smoothie?\n", "bold cyan");
		my $ans = readline();
		chomp($ans);
		if ($ans =~ /^[Yy](?:es)?/) {
			system("/bin/mkdir -p $modsa_home") unless ( -d $modsa_home );
			system("/bin/mkdir -p $modsa_home/$mod_name") unless ( -d "$modsa_home/$mod_name");
			system("/bin/cp -rf * $modsa_home/$mod_name/");
			chdir("$modsa_home/$mod_name");
			print colored("Whitelisting GREEN IP....\n", "bold cyan");
			my @newlines;
			open CONFIN, "<etc/fail2ban/jail.conf" or die colored("There was a problem opening jail.conf: $!", "bold red");
			while (my $line = <CONFIN>) {
				chomp($line);
				if ($line =~ /^ignoreip/) {
					$line .= " $ethernet_settings{'GREEN_NETADDRESS'}/$mask2cidr{$ethernet_settings{'GREEN_NETMASK'}}";
				}
				push @newlines, $line;
			}
			close CONFIN or die colored("There was a problem closing jail.conf: $!", "bold red");
			open CONFOUT, ">/tmp/fail2ban.tmp.conf" or die colored("Couldn't open output tmp file: $!", "bold red");
			foreach my $line ( @newlines ) {
				print CONFOUT $line."\n";
			}
			close CONFOUT or die colored("There was a problem closing output tmp file: $!", "bold red");
			system("/bin/cp -f /tmp/fail2ban.tmp.conf $modsa_home/$mod_name/etc/fail2ban/jail.conf");
			print colored("Patching /etc/bashrc....\b", "bold cyan");
			system("/bin/grep -q 'modification by swe-fail2ban' /etc/bashrc || /bin/cat _etc_bashrc.add >> /etc/bashrc");
			chdir("$mods_home");
			system("/bin/ln -snf ../mods-available/fail2ban fail2ban");
			# fail2ban insists that stuff be in /etc/fail2ban, even with the alternate config
			chdir("/etc/");
			system("/bin/ln -snf $mods_home/fail2ban/etc/fail2ban fail2ban");
			system("/bin/touch $modsa_home/$mod_name/installed");
			print colored("The fail2ban mod for Smoothwall Express should now be enabled and configured.\n", "bold cyan");
			print colored("To use the fail2ban-client command immediately, \"source /etc/bashrc\".  Otherwise, log out, then back in.\n", "bold cyan");
		} else {
			print colored("Quitting.\n", "bold red");
			exit 0;
		}
	}
	when ("$modsa_home/$mod_name") {
		print colored("Looks like you're already in the mod home directory.  Less to do!   \nWould you like to install this mod to your smoothie?\n", "bold cyan");
		my $ans = readline();
		chomp($ans);
		if ($ans =~ /^[Yy](?:es)?/) {
			print colored("Whitelisting GREEN IP....\n", "bold cyan");
			my @newlines;
			open CONFIN, "<etc/fail2ban/jail.conf" or die colored("There was a problem opening jail.conf: $!", "bold red");
			while (my $line = <CONFIN>) {
				chomp($line);
				if ($line =~ /^ignoreip/) {
					$line .= " $ethernet_settings{'GREEN_NETADDRESS'}/$mask2cidr{$ethernet_settings{'GREEN_NETMASK'}}";
				}
				push @newlines, $line;
			}
			close CONFIN or die colored("There was a problem closing jail.conf: $!", "bold red");
			open CONFOUT, ">/tmp/fail2ban.tmp.conf" or die colored("Couldn't open output tmp file: $!", "bold red");
			foreach my $line ( @newlines ) {
				print CONFOUT $line."\n";
			}
			close CONFOUT or die colored("There was a problem closing output tmp file: $!", "bold red");
			system("/bin/cp -f /tmp/fail2ban.tmp.conf $modsa_home/$mod_name/etc/fail2ban/jail.conf");
			print colored("Patching /etc/bashrc....\b", "bold cyan");
			system("/bin/grep -q 'modification by swe-fail2ban' /etc/bashrc || /bin/cat _etc_bashrc.add >> /etc/bashrc");
			chdir("$mods_home");
			system("/bin/ln -snf ../mods-available/fail2ban fail2ban");
			# fail2ban insists that stuff be in /etc/fail2ban, even with the alternate config
			chdir("/etc/");
			system("/bin/ln -snf $mods_home/fail2ban/etc/fail2ban fail2ban");
			system("/bin/touch $modsa_home/$mod_name/installed");
			print colored("The fail2ban mod for Smoothwall Express should now be enabled and configured.\n", "bold cyan");
			print colored("To use the fail2ban-client command immediately, \"source /etc/bashrc\".  Otherwise, log out, then back in.\n", "bold cyan");
		} else {
			print colored("Quitting.\n", "bold red");
			exit 0;
		}
	}
	default { die colored("Unrecognized installation directory!", "bold red"); }
}
